---
title: "Teachers' Corner"
output:
  html_document:
    css: "styles.css"
---

Hello! This page contains a few additional resources that aim to inspire how you might use this module in your classroom. Feel free to adapt any suggestions to your class needs.

<h2>Definitions</h2>
<div style="border: medium dotted #FFEDB1;">
<ol><li>Identify flaws in definitions that limit possible examples of randomness.</li>
<li>Build a better definition of randomness, clarifying important aspects of random examples.</li>
</ol>
</div>
<br>
<center><iframe width="560" height="315" src="https://www.youtube.com/embed/iGc6arzHIoY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></center>

<br>
<h2>Distributions and Randomness</h2>
<div style="border: medium dotted #FFEDB1;">
<ol><li>Consider how random events might be expressed over an area using knowledge of distributions.</li>
<li>Explore the relationship between small samples, large samples, and distributions.</li>
<li>Consider how randomness can effect waiting times and build into different distributions.</li>
<li>Recognise the process of random sampling from distributions.</li></ol>
</div>
<br>
<h3 style="text-align: center;">Spatial Randomness</h3>
<center><iframe width="560" height="315" src="https://www.youtube.com/embed/vvcfloq8KaU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></center>

<br>

<h3 style="text-align: center;">Waiting Times</h3>
<center><iframe width="560" height="315" src="https://www.youtube.com/embed/6_zhAPdi8Uk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></center>
<br>
You can find more documentation on Scampy <a href = https://new.censusatschool.org.nz/wp-content/uploads/2019/09/scampy_documentation.pdf target = "_blank">here</a>.

<br>

<h2>Other Examples</h2>
<p>This section of the Randomness Module provides additional examples, highlighting how randomness may be seen in everyday life, biology, chemistry, and physics. It is recommended that these are used to further explore randomness after considering the definition of randomness and it's relationship with distributions.</p>
<br>
<div style="border: medium dotted #FFEDB1;">
<ol><li>Explore and discuss everyday examples using the previous skills attained in the definition and distribution sections.</li>
<li>...</li>
<li>Explore diffusion as an example of randomness in chemistry with connections to sample size and fluctuations about the mean.</li>
<li>Consider how random events build into a distribution with a radioactive decay example.</li></ol>
</div>
<br>