---
title: "The Representativeness Heuristic"
output:
  html_document:
    css: "styles.css"
---
Most research, starting with the original paper by Tversky and Kahneman (1974), appears to suggest that the representativeness heuristic is the primary bias underpinning randomness misconceptions. 

The representativeness heuristic is where people judge the likelihood of an outcome based on how representative it is of the broader population or event. 

Consider a sequence of ten coin-flips with only one outcome of tails – it may be judged that this sequence of outcomes is unlikely as a 50:50 ratio of heads to tails is more consistent with what we may expect from a fair coin. 

Other examples include an insensitivity of prior probability of outcomes (where <a href = "https://thedecisionlab.com/biases/base-rate-fallacy/" target = "blank">base-rate</a> frequencies are overlooked), and an insensitivity to sample size (where the effect of <a href = https://fs.blog/2013/05/mental-model-bias-from-insensitivity-to-sample-size/ target = "blank">sample size</a> is ignored).

Randomness is prone to judgment using the representativeness heuristic. In judging uncertain probabilities or random sequences of events, intuitive responses can lead to misconceptions about how probability and randomness work in the world.

<div class="interact_responsive_padding" style="padding:100% 0 0 0;position:relative;margin-bottom:5px;"><div class="interact_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><iframe id="interactApp60a2f7ea7e99a30017369ce9" width="100%" height="100%" style="border:none;max-width:100%;margin:0;" allowTransparency="true" frameborder="0" src="https://quiz.tryinteract.com/#/60a2f7ea7e99a30017369ce9/q/1?method=iframe&mobile=1"></iframe></div></div>
